# Generated by Django 4.2.1 on 2023-05-09 16:53

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("subtitle", models.CharField(max_length=100)),
                (
                    "photo",
                    stdimage.models.StdImageField(
                        force_min_size=False, upload_to="photos", variations={}
                    ),
                ),
                (
                    "thumb",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to="thumbnails",
                        variations={"thumbnail": {"height": 180, "width": 270}},
                    ),
                ),
            ],
            options={
                "verbose_name": ("Photo",),
                "verbose_name_plural": "Photos",
            },
        ),
    ]
