# Generated by Django 4.2.1 on 2023-05-09 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={
                "permissions": [
                    ("can_edit_photo", "Can edit photo"),
                    ("can_delete_photo", "Can delete photo"),
                ],
                "verbose_name": ("Photo",),
                "verbose_name_plural": ("Photos",),
            },
        ),
        migrations.AddField(
            model_name="photo",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
