# Generated by Django 4.2.1 on 2023-05-09 17:34

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_photo_options_photo_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={
                "permissions": [
                    ("can_edit_photo", "Can edit photo"),
                    ("can_delete_photo", "Can delete photo"),
                ],
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
            },
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=stdimage.models.StdImageField(
                force_min_size=False, upload_to="profile_pictures", variations={}
            ),
        ),
    ]
