# Generated by Django 4.2.1 on 2023-05-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_photo_options_alter_photo_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="tags",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
