# Generated by Django 4.2.1 on 2023-05-09 20:10

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_photo_created_at_photo_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="thumb",
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=stdimage.models.StdImageField(
                force_min_size=False,
                upload_to="profile_pictures",
                variations={"thumbnail": {"crop": True, "height": 100, "width": 100}},
            ),
        ),
    ]
