# Generated by Django 4.2.1 on 2023-05-18 16:29

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_photo_thumb_alter_photo_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="tags",
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=stdimage.models.StdImageField(
                force_min_size=False,
                upload_to="profile_pictures",
                variations={"thumbnail": {"crop": True, "height": 180, "width": 270}},
            ),
        ),
    ]
