# Generated by Django 4.2.1 on 2023-05-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_customuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whos_following',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
